version: '3.4'

services:  
  eurekaserver:
    image: sonaligarg15/bankingproject:eureka-server
    expose:
     - "8761"
    ports:
     - "8761:8761"
    hostname: eureka-server
    container_name: eurekaserver

  configserver:
    image: sonaligarg15/configserver:latest
    expose:
     - "8888"
    ports:
     - "8888:8888"
    hostname: configserver
    container_name: configservercontainersonali

  accountservice:
    image: ${DOCKER_REGISTRY-}accountservice
    build:
      context: .
      dockerfile: AccountAPI/Dockerfile
    expose:
     - "80"
    ports:
     - "5002:80"
    depends_on:
     - eurekaserver
    hostname: accountservice
    container_name: accountcontainer

  transactionservice:
    image: ${DOCKER_REGISTRY-}transactionservice
    build:
      context: .
      dockerfile: TransactionAPI/Dockerfile
    expose:
     - "80"
    ports:
     - "5006:80"
    depends_on:
     - eurekaserver
    container_name: transactioncontainer

  userservice:
    image: ${DOCKER_REGISTRY-}userservice
    build:
      context: .
      dockerfile: UserAPI/Dockerfile
    expose:
     - "80"
    ports:
     - "5008:80"
    depends_on:
     - eurekaserver
    container_name: usercontainer

  gateway:
    image: ${DOCKER_REGISTRY-}gateway
    build:
      context: .
      dockerfile: Gateway/Dockerfile
    expose:
     - "80"
    ports:
     - "5000:80"
    depends_on:
     - eurekaserver
     - userservice
     - transactionservice
     - accountservice
    container_name: gatewaycontainer


